// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-D8SPypjU21mUQC7yHjezczRqpNa9jN0',
    appId: '1:715226936174:web:eff7e1cd0b9b5bb959c77f',
    messagingSenderId: '715226936174',
    projectId: 'my-app-d48da',
    authDomain: 'my-app-d48da.firebaseapp.com',
    storageBucket: 'my-app-d48da.firebasestorage.app',
    measurementId: 'G-9YNZWF3NZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhU7jz28B0eqYqOsTtldi4_5weiJeL8yA',
    appId: '1:715226936174:android:df5a57ac03e679fe59c77f',
    messagingSenderId: '715226936174',
    projectId: 'my-app-d48da',
    storageBucket: 'my-app-d48da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVaZ7lI8ZadxyokTzqXxWhI4YuUsJEgTs',
    appId: '1:715226936174:ios:2e565715f54dbc5c59c77f',
    messagingSenderId: '715226936174',
    projectId: 'my-app-d48da',
    storageBucket: 'my-app-d48da.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-D8SPypjU21mUQC7yHjezczRqpNa9jN0',
    appId: '1:715226936174:web:3ee9d01756ab3b9859c77f',
    messagingSenderId: '715226936174',
    projectId: 'my-app-d48da',
    authDomain: 'my-app-d48da.firebaseapp.com',
    storageBucket: 'my-app-d48da.firebasestorage.app',
    measurementId: 'G-TGLY9EWGVR',
  );
}
