// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0L59qyNRJws-FLV44tNW_Vn8AwvdEFuA',
    appId: '1:1077840112766:web:1740da14b1160d39ac7c2f',
    messagingSenderId: '1077840112766',
    projectId: 'posty-a1f29',
    authDomain: 'posty-a1f29.firebaseapp.com',
    storageBucket: 'posty-a1f29.firebasestorage.app',
    measurementId: 'G-SB4BBXN5H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAK4j__EM39W9BBbUlBXLjsMrqN9DEUTs',
    appId: '1:1077840112766:android:7562841ff3ce58deac7c2f',
    messagingSenderId: '1077840112766',
    projectId: 'posty-a1f29',
    storageBucket: 'posty-a1f29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkT3Oqtm3Esy2YEeclcwYem_TB1fogPdM',
    appId: '1:1077840112766:ios:675f9685cf315020ac7c2f',
    messagingSenderId: '1077840112766',
    projectId: 'posty-a1f29',
    storageBucket: 'posty-a1f29.firebasestorage.app',
    iosBundleId: 'com.example.practiceApp',
  );
}
